feat: cohortdefiners return validatedframes
Aarhus-Psychiatry-Research/psycop-common pull request #711
Opened 2024-01-16 14:07 UTC by sarakolding

Automatically created PR from invoke

2024-01-16 14:31 UTC, sarakolding commented
@MartinBernstorff what I think is happening is that the PredictionTimeCollator (in seq models) is no longer runtime_checkable since it contains CohortDefiner, and CohortDefiner now uses the ValidatedFrame which is not runtime_checkable. But I'm pretty lost (and Lasse is too), so maybe we can talk about it tomorrow 🐒

2024-01-16 14:32 UTC, sarakolding commented
(ps it is not done - I can't run the tests because of the error)

2024-01-17 07:23 UTC, MartinBernstorff commented
Sure thing. I'm here today; I'll wait until we can talk 👍

2024-01-17 09:30 UTC, sarakolding commented
thoughts: more cols/validators? e.g., uuid col with a unique rule?
also, maybe we should make a getattribute method or something, so the frame can be called from the instance, instead of the attribute?

2024-01-17 14:00 UTC, MartinBernstorff requested changes

2024-01-17 14:21 UTC, sarakolding commented on psycop/common/test_cohort_definition.py
>          entity_id_col_name="entity_id",
works because it is only used for counting, and get_counts=False

2024-01-17 14:32 UTC, MartinBernstorff approved these changes

2024-01-17 14:37 UTC, merged